#!/usr/bin/env bash
set -euo pipefail

# ─── CLASHD27 VPS Deploy Script ───────────────────────────────────────
# Deploys clashd27 engine to VPS and configures PM2 + Bieb cron
# Target: root@178.104.55.41
# ──────────────────────────────────────────────────────────────────────

VPS_HOST="root@178.104.55.41"
VPS_DIR="/root/clashd27"
VPS_DATA_DIR="/root/clashd27-data/promise-library"
LOCAL_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "═══════════════════════════════════════════════"
echo "  CLASHD27 — Deploy to VPS"
echo "═══════════════════════════════════════════════"
echo ""

# ─── Step 1: Sync source code ────────────────────────────────────────
echo "[1/4] Syncing source code to ${VPS_HOST}:${VPS_DIR}/ ..."

rsync -avz --delete \
  --exclude 'node_modules' \
  --exclude '.git' \
  --exclude 'data/cache' \
  --exclude '.env' \
  "${LOCAL_DIR}/" "${VPS_HOST}:${VPS_DIR}/"

echo "      Done."
echo ""

# ─── Step 2: Install dependencies on VPS ─────────────────────────────
echo "[2/4] Installing node_modules on VPS ..."

ssh "${VPS_HOST}" bash -s <<'REMOTE_INSTALL'
set -euo pipefail
cd /root/clashd27
npm install --omit=dev --no-audit --no-fund 2>&1 | tail -3
echo "      node_modules installed."
REMOTE_INSTALL

echo ""

# ─── Step 3: Configure and start PM2 ─────────────────────────────────
echo "[3/4] Configuring PM2 on VPS ..."

ssh "${VPS_HOST}" bash -s <<'REMOTE_PM2'
set -euo pipefail

VPS_DIR="/root/clashd27"
VPS_DATA_DIR="/root/clashd27-data/promise-library"
BIEB_LATEST="${VPS_DATA_DIR}/latest-cube.json"

# Ensure data directory exists
mkdir -p "${VPS_DATA_DIR}"

# Write VPS-specific ecosystem config
cat > "${VPS_DIR}/ecosystem.vps.config.js" <<'ECOSYSTEM'
// CLASHD27 VPS PM2 config — generated by deploy-vps.sh
// Secrets loaded by the app via dotenv from /root/.secrets/clashd27.env

module.exports = {
  apps: [
    {
      name: 'clashd27-bot',
      script: 'bot.js',
      cwd: '/root/clashd27',
      watch: false,
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      env: {
        NODE_ENV: 'production',
        CLASHD27_BIEB_LATEST_PATH: '/root/clashd27-data/promise-library/latest-cube.json'
      }
    },
    {
      name: 'clashd27-dashboard',
      script: 'dashboard/server.js',
      cwd: '/root/clashd27',
      watch: false,
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      env: {
        NODE_ENV: 'production',
        CLASHD27_BIEB_LATEST_PATH: '/root/clashd27-data/promise-library/latest-cube.json'
      }
    },
    {
      name: 'clashd27-public',
      script: 'public-site/server.js',
      cwd: '/root/clashd27',
      watch: false,
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      env: {
        NODE_ENV: 'production',
        PUBLIC_PORT: 3028,
        CLASHD27_BIEB_LATEST_PATH: '/root/clashd27-data/promise-library/latest-cube.json'
      }
    }
  ]
};
ECOSYSTEM

# Stop existing instances (ignore errors if not running)
pm2 delete clashd27-bot clashd27-dashboard clashd27-public 2>/dev/null || true

# Start all apps with VPS ecosystem config
cd "${VPS_DIR}"
pm2 start ecosystem.vps.config.js

# Save PM2 process list so it restarts on server reboot
pm2 save

# Ensure pm2 startup hook is configured
pm2 startup 2>/dev/null || true

echo "      PM2 apps started."
pm2 list
REMOTE_PM2

echo ""

# ─── Step 4: Set up Bieb shuffle cron (every 10 minutes) ─────────────
echo "[4/4] Setting up Bieb shuffle cron (every 10 min) ..."

ssh "${VPS_HOST}" bash -s <<'REMOTE_CRON'
set -euo pipefail

VPS_DIR="/root/clashd27"
VPS_DATA_DIR="/root/clashd27-data/promise-library"
BIEB_LATEST="${VPS_DATA_DIR}/latest-cube.json"
LOG_FILE="/root/clashd27-data/bieb-shuffle.log"

# Write the shuffle runner script
cat > "${VPS_DIR}/bin/bieb-shuffle-cron.sh" <<SHUFFLESCRIPT
#!/usr/bin/env bash
set -euo pipefail

cd "${VPS_DIR}"

# Load env vars (same as the app does)
if [ -f /root/.secrets/clashd27.env ]; then
  set -a
  source /root/.secrets/clashd27.env
  set +a
fi

export CLASHD27_BIEB_LATEST_PATH="${BIEB_LATEST}"

# Run the cube shuffle
node bin/promise-cube-run.js >> "${LOG_FILE}" 2>&1

# Copy latest cube to the external data path
mkdir -p "${VPS_DATA_DIR}"
cp "${VPS_DIR}/data/promise-library/latest-cube.json" "${BIEB_LATEST}" 2>/dev/null || true

echo "[\\$(date -Iseconds)] Bieb shuffle complete" >> "${LOG_FILE}"
SHUFFLESCRIPT

chmod +x "${VPS_DIR}/bin/bieb-shuffle-cron.sh"

# Install cron job — remove old entry first, then add
CRON_CMD="${VPS_DIR}/bin/bieb-shuffle-cron.sh"
( crontab -l 2>/dev/null | grep -v "bieb-shuffle-cron" ; \
  echo "*/10 * * * * ${CRON_CMD}" ) | crontab -

echo "      Cron installed:"
crontab -l | grep bieb-shuffle
REMOTE_CRON

echo ""
echo "═══════════════════════════════════════════════"
echo "  Deploy complete!"
echo ""
echo "  Engine:    ${VPS_HOST}:${VPS_DIR}/"
echo "  Dashboard: http://178.104.55.41:3027"
echo "  Public:    http://178.104.55.41:3028"
echo "  Bieb:      ${VPS_DATA_DIR}/latest-cube.json"
echo "  Cron:      every 10 min — Bieb shuffle"
echo "  Logs:      /root/clashd27-data/bieb-shuffle.log"
echo "═══════════════════════════════════════════════"
