// CLASHD27 VPS PM2 config — generated by deploy-vps.sh
// Secrets loaded by the app via dotenv from /root/.secrets/clashd27.env

module.exports = {
  apps: [
    {
      name: 'clashd27-bot',
      script: 'bot.js',
      cwd: '/root/clashd27',
      watch: false,
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      env: {
        NODE_ENV: 'production',
        CLASHD27_BIEB_LATEST_PATH: '/root/clashd27-data/promise-library/latest-cube.json'
      }
    },
    {
      name: 'clashd27-dashboard',
      script: 'dashboard/server.js',
      cwd: '/root/clashd27',
      watch: false,
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      env: {
        NODE_ENV: 'production',
        CLASHD27_BIEB_LATEST_PATH: '/root/clashd27-data/promise-library/latest-cube.json'
      }
    },
    {
      name: 'clashd27-public',
      script: 'public-site/server.js',
      cwd: '/root/clashd27',
      watch: false,
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      env: {
        NODE_ENV: 'production',
        PUBLIC_PORT: 3028,
        CLASHD27_BIEB_LATEST_PATH: '/root/clashd27-data/promise-library/latest-cube.json'
      }
    }
  ]
};
