/**
 * CLASHD-27 Insights Storage
 * Stores and manages research insights generated by agents
 */

const fs = require('fs');
const path = require('path');

const INSIGHTS_FILE = path.join(__dirname, '..', 'data', 'insights.json');
const MAX_INSIGHTS = 200;

let insights = [];
let insightIdCounter = 1;

function load() {
  try {
    if (fs.existsSync(INSIGHTS_FILE)) {
      const data = JSON.parse(fs.readFileSync(INSIGHTS_FILE, 'utf8'));
      insights = data.insights || [];
      insightIdCounter = data.nextId || (insights.length > 0 ? Math.max(...insights.map(i => i.id)) + 1 : 1);
      console.log(`[INSIGHTS] Loaded ${insights.length} insights`);
    }
  } catch (err) {
    console.error('[INSIGHTS] Load failed:', err.message);
    insights = [];
  }
}

function save() {
  try {
    const dir = path.dirname(INSIGHTS_FILE);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(INSIGHTS_FILE, JSON.stringify({ insights, nextId: insightIdCounter }, null, 2));
  } catch (err) {
    console.error('[INSIGHTS] Save failed:', err.message);
  }
}

/**
 * Add a new insight
 * @param {Object} params
 * @param {string} params.type - CELL_INSIGHT, BOND_INSIGHT, or DISCOVERY
 * @param {number} params.tick
 * @param {number} params.cell
 * @param {string} params.cellLabel
 * @param {number} params.layer
 * @param {string} params.agentName - single agent or comma-separated for bonds
 * @param {string} params.content - the generated insight text
 * @param {Object} [params.metadata] - additional data (agent2, cell2Label, etc.)
 */
function addInsight({ type, tick, cell, cellLabel, layer, agentName, content, metadata = {} }) {
  const insight = {
    id: insightIdCounter++,
    type,
    tick,
    cell,
    cellLabel,
    layer,
    agentName,
    content,
    metadata,
    timestamp: Date.now()
  };

  insights.push(insight);

  // Keep only last MAX_INSIGHTS
  if (insights.length > MAX_INSIGHTS) {
    insights = insights.slice(-MAX_INSIGHTS);
  }

  save();
  console.log(`[INSIGHTS] Added ${type}: "${content.slice(0, 50)}..."`);
  return insight;
}

/**
 * Get latest insights
 * @param {number} limit - max number to return
 * @returns {Array} insights, newest first
 */
function getLatest(limit = 50) {
  return [...insights].reverse().slice(0, limit);
}

/**
 * Get insights for a specific cell
 * @param {number} cell
 * @param {number} limit
 * @returns {Array}
 */
function getByCell(cell, limit = 20) {
  return insights.filter(i => i.cell === cell).reverse().slice(0, limit);
}

/**
 * Get insights by type
 * @param {string} type
 * @param {number} limit
 * @returns {Array}
 */
function getByType(type, limit = 50) {
  return insights.filter(i => i.type === type).reverse().slice(0, limit);
}

/**
 * Get all insights (for debugging)
 */
function getAll() {
  return insights;
}

// Load on module init
load();

module.exports = {
  addInsight,
  getLatest,
  getByCell,
  getByType,
  getAll,
  load,
  save
};
